/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[notfound]': RouteRecordInfo<'/[notfound]', '/:notfound', { notfound: ParamValue<true> }, { notfound: ParamValue<false> }>,
    '/playlists/': RouteRecordInfo<'/playlists/', '/playlists', Record<never, never>, Record<never, never>>,
    '/playlists/[id]': RouteRecordInfo<'/playlists/[id]', '/playlists/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/playlists/mine/': RouteRecordInfo<'/playlists/mine/', '/playlists/mine', Record<never, never>, Record<never, never>>,
  }
}
